Repository SpaceDice9/exestack, pull requests merged in 2024-09, with the labels that each got.

#8 Remove TODO
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  TODO.md
Labels: documentation

#9 Update Ode Script Editor to latest version
  CHANGELOG.md
  src/Exestack/Applications/BytExecutor2.luau
  src/Exestack/Modules/OdeScriptEditor/.src.luau
  src/Exestack/Modules/OdeScriptEditor/Hooks/AutoIndent.luau
  src/Exestack/Modules/OdeScriptEditor/Hooks/AutoWrap.luau
  src/Exestack/Modules/OdeScriptEditor/Modules/LuaTable.luau
  src/Exestack/Modules/OdeScriptEditor/Modules/fastlexer.luau
  src/Exestack/Modules/OdeScriptEditor/Modules/language.luau
  src/Exestack/Modules/OdeScriptEditor/Modules/lexer.luau
  src/Exestack/Modules/OdeScriptEditor/OSEBackground/.data.json
  src/Exestack/Modules/OdeScriptEditor/OSEBackground/CodeField/.data.json
  src/Exestack/Modules/OdeScriptEditor/OSEBackground/LineNumberBackground/.data.json
  src/Exestack/Modules/OdeScriptEditor/OSEBackground/LineNumberContainer/.data.json
  src/Exestack/Modules/OdeScriptEditor/OSEBackground/RichOverlayContainer/.data.json
  src/Exestack/Modules/OdeScriptEditor/OSEBackground/RichOverlayContainer/ShiftContainer/.data.json
  src/Exestack/Modules/OdeScriptEditor/Storage/LineNumber/.data.json
  src/Exestack/Modules/OdeScriptEditor/Storage/RichOverlayLabel/.data.json
  src/Exestack/UI/BytExecutorBackground/ParentContainer/.data.json
  src/Exestack/UI/BytExecutorBackground/ParentContainer/ParentImage/.data.json
  src/Exestack/UI/BytExecutorBackground/ParentContainer/ParentName/.data.json
  src/Exestack/UI/BytExecutorBackground/ParentContainer/Separater/.data.json
Labels: bug, enhancement

#4 Change element theming to be more similar to Studio explorer
  CHANGELOG.md
  src/Exestack/Applications/BytExecutor2.luau
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Delete/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Execute/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Export/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Pause/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Resume/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Status/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/Terminate/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/Interactions/UIListLayout/.data.json
  src/Exestack/Storage/BytExecutor2/Byt_Preset/SelectionStroke/.data.json
  src/Exestack/Storage/BytExecutor2/Folder_Preset/ConfirmInteractions/Cancel/.data.json
  src/Exestack/Storage/BytExecutor2/Folder_Preset/ConfirmInteractions/Confirm/.data.json
  src/Exestack/Storage/BytExecutor2/Folder_Preset/Interactions/Delete/.data.json
  src/Exestack/Storage/BytExecutor2/Folder_Preset/Interactions/Export/.data.json
  src/Exestack/Storage/BytExecutor2/Folder_Preset/Interactions/UIListLayout/.data.json
  src/Exestack/Storage/BytExecutor2/Folder_Preset/SelectionStroke/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Delete/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Execute/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Export/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Pause/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Resume/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Status/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/Terminate/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/Interactions/UIListLayout/.data.json
  src/Exestack/Storage/BytExecutor2/LocalByt_Preset/SelectionStroke/.data.json
  src/Exestack/Storage/BytExecutor2/Snippet_Preset/Interactions/Delete/.data.json
  src/Exestack/Storage/BytExecutor2/Snippet_Preset/Interactions/Export/.data.json
  src/Exestack/Storage/BytExecutor2/Snippet_Preset/Interactions/UIListLayout/.data.json
  src/Exestack/Storage/BytExecutor2/Snippet_Preset/SelectionStroke/.data.json
Labels: enhancement
